json.extract! @score, 
              :id, 
              :user_id,
              :project_id,
              :duration, 
              :specs, 
              :succeeded, 
              :failed, 
              :pending, 
              :created_at, 
              :updated_at
